### ISSUE TITLE
How should input.json accomodate three lists of files?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/heatmap-scatter-dash#157]
I think we want a short term solution, and something for the long term which will improve the usability in Refinery.

For the short term solution, I'd be happy with a triple of lists: I need some kind of structure because the aws runner needs to encode its arguments in input.json. The current structure is for practical purposes unusable in Refinery, so I wouldn't worry too much that a triple couldn't even be constructed by Refinery, though it could be done other ways.

The longer term work is covered by https://github.com/refinery-platform/refinery-platform/issues/2564

**Comment by scottx611x** [comment]
@mccalluc At the moment for a similar input structure we only support a Pair of lists or a List of lists (without a length constraint).
 I would imagine that adding input length constraints in our ToolDefinitions wouldn't be too hard

**Comment by mccalluc** [comment]
I'm not sure that's a good direction: It's unclear that users can even populate a pair correctly. I think we want to distinguish a short term fix for the visualization (which might not be supported by Refinery) and a longer time labelled values approach.

**Comment by mccalluc** [comment]
Decided to abandon this front, and instead we just sniff to determine file types. PR #210
